name: Java Build and Deploy

on:
  push:
    branches: [master]

jobs:
  Construir-Acrtefacto:
    runs-on: ubuntu-latest
    
    steps:
      - name: Crear carpeta
        run: mkdir downloads
        
      - name: Ir a downloads
        run: cd downloads
        
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compilar con Maven
        run: mvn clean install 
      
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: Descargas
          path: downloads
