name: Java Build and Deploy

on:
  push:
    branches: [master]

jobs:
  Construir-Acrtefacto:
    runs-on: ubuntu-latest
    
    steps:
      - name: Crear directorio virtual
        run: mkdir downloads
      
      - name: Ver repositorio
        uses: actions/checkout@v4

      - name: Interpretar Java
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '21'
      
      - name: Correer Java
        run: java App.java
      
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
            name: my-artifact
            path: downloads/
