name: Java Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Crear directorio virtual
      - run: mkdir downloads
      
      - name: Interpretar Java
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '21'
      - run: java App.java
      
      - name: Subir artefacto
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: downloads/
