name: Java Build and Deploy

on:
  push:
    branches: [master]

jobs:
  Construir-Acrtefacto:
    runs-on: ubuntu-latest
    
    steps:
      - name: Crear directorio virtual
        run: mkdir downloads
      
      - name: Ver repositorio
        uses: actions/checkout@v4

      - name: Interpretar Java
        uses: actions/checkout@v2
        
      - name: Compilar   
        uses: joschi/setup-jdk@v2
        with:
            java-version: '11' # The OpenJDK version to make available on the path
            architecture: 'x64' # defaults to 'x64'
            
      - name: Ejecutar app      
        run: java -cp java App
      
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
            name: my-artifact
            path: downloads/
