name: Java Build and Deploy

on:
  push:
    branches: [master]

jobs:
  Construir-Acrtefacto:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compilar Manual
        run: |
          mkdir downloads
          cd src
          javac App.java
          ls -R
        # cp -r . downloads
            
        
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: Descargas
          path: /home/runner/work/actionJava/actionJava/src/
