name: Java Build and Deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v2

    - name: Configurar JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Compilar y Empaquetar con Maven
      run: mvn -B package --file pom.xml

    - name: Subir archivos compilados
      uses: actions/upload-artifact@v2
      with:
        name: compiled-files
        path: target/*.jar  

    - name: Desplegar en GitHub Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/*.jar  
        asset_name: my-app.jar  
        asset_content_type: application/java-archive
        token: ${{ secrets.GITHUB_TOKEN }}
