name: Java Build and Deploy

on:
  push:
    branches: [master]

jobs:
  Construir-Acrtefacto:
    runs-on: ubuntu-latest
    
    steps:
      - name: Crear directorio virtual
        run: mkdir downloads
      
      - name: Ver repositorio
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
            name: my-artifact
            path: downloads/
